version: '3.8'

services:
  web:
    build: .
    ports:
      - "10005:5002"
    volumes:
      - /home/dx2331lxz/data/python/download_app:/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_PATH=/data/versions.db
      - UPLOAD_FOLDER=/data/uploads
    restart: unless-stopped